### ISSUE TITLE
Copy links

### ISSUE THREAD

**Issue by JesusLopezMadrid** [Tomsgu/PDFMerger#1]
Hi,
Could it be done to also copy the links that have the pdf?

**Comment by Tomsgu** [comment]
Hi @JesusLopezMadrid,
what do you mean by this? Do you have any example?

**Comment by JesusLopezMadrid** [comment]
I have 2 pdf, which have images with embedded link, when I click another browser window opens. But when merge pdf, those links disappear.

**Comment by pionl** [comment]
@JesusLopezMadrid FYI https://github.com/Setasign/FPDI/issues/162

**Comment by JanSlabon** [comment]
In FPDI 2.4.0 you can import PDF pages with external links now: https://github.com/Setasign/FPDI/releases/tag/v2.4.0
For backwards compatibility you need to activate this. See here for more details: https://www.setasign.com/news-archive/fpdi-2.4.0-released/

**Comment by Tomsgu** [comment]
Sorry to wait that much with the release. I completely forgot on that.
Released in 0.5.0

**Comment by JanSlabon** [comment]
You should also update your composer.json to `"setasign/fpdi": "^2.4"`.

**Comment by Tomsgu** [comment]
It's still possible to use older versions of fpdi with those changes. Just without the new feature. 
I will change it in a major version.
