### ISSUE TITLE
Deprecations in symfony 6.3

### ISSUE THREAD

**Issue by thenerka1** [Tomsgu/PDFMerger#13]
1.
Method "Symfony\Component\DependencyInjection\Extension\ExtensionInterface::load()" might add "void" as a native return type declaration in the future. Do the same in implementation "Tomsgu\PdfMergerBundle\DependencyInjection\TomsguPdfMergerExtension" now to avoid errors or add an explicit @return annotation to suppress this message.

2.
Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future. Do the same in implementation "Tomsgu\PdfMergerBundle\DependencyInjection\Configuration" now to avoid errors or add an explicit @return annotation to suppress this message.

**Comment by Tomsgu** [comment]
This is an issue of PDFMergerBundle and it has been fixed in 0.5.0 version: [Tomsgu/PDFMergerBundle](https://github.com/Tomsgu/PDFMergerBundle/releases/tag/v0.5.0)
