### ISSUE TITLE
Provide possibilty to merge binary data pdf

### ISSUE THREAD

**Issue by remoteclient** [Tomsgu/PDFMerger#2]
Right now we use symfony and snappy to generate pdfs. Instead of saving them to disk we send the binary directly in the response.

What is needed, is the possibility to merge the generated binary pdfs on the fly and get binary data back.

**Comment by Tomsgu** [comment]
Hey, that seems like a good addition. Take a look at #3.

**Comment by Tomsgu** [comment]
Closing as a new version was tagged with this feature.

**Comment by remoteclient** [comment]
Hey, thank you for this PR. I am also really sorry to come back to you so late. I would like to try the changes. Unfortunately composer does not allow me to upgrade the pdf-merger:
```  Problem 1
    - Root composer.json requires tomsgu/pdf-merger-bundle ^0.4.0 -> satisfiable by tomsgu/pdf-merger-bundle[v0.4].
    - tomsgu/pdf-merger-bundle v0.4 requires tomsgu/pdf-merger ^0.2 -> found tomsgu/pdf-merger[v0.2] but it conflicts with your root composer.json require (^0.4).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

I also tried to manually set the version in the composer file, without success:
```
        "tomsgu/pdf-merger": "^0.4",
        "tomsgu/pdf-merger-bundle": "^0.4.0",
```

**Comment by Tomsgu** [comment]
Yeah you're right. I have fixed the bundle's composer requirements. You can now just require tomsgu/pdf-merger-bundle and it will download the newest 0.* version of the lib.

**Comment by remoteclient** [comment]
I had time for a first test. Unfortunately I get a FileNotFoundException:

```
        if (is_string($file) && file_exists($file) === false) {
            throw new FileNotFoundException();
        }
```
coming from the constructor line 54 in PdfFile.

So in our case `is_string($file)` returns true.

**Comment by Tomsgu** [comment]
You should pass a resource instead of string. For example:
```php
$stream = fopen('php://memory', 'rw');
fputs($stream, $pdfInString);
new PdfFile($stream);
```

**Comment by remoteclient** [comment]
Thanks again. This way it works.:)

**Comment by Tomsgu** [comment]
Great! Glad to help you.
